# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: pnpm install # runs during prebuild
    command: pnpm exec nx serve home

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4200
    onOpen: open-preview
