name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: pnpm install
      - run: pnpm nx workspace-lint
      - run: pnpm nx format:check
      - run: pnpm nx affected --target=lint --parallel=3
      - run: pnpm nx affected --target=test --parallel=3 --ci --code-coverage
      - run: pnpm nx affected --target=build --parallel=3
